global:
  # default scrape_interval
  scrape_interval: 30s

scrape_configs:


# Gateway
  - job_name: 'gateway'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.0.6:9100']

  - job_name: 'gateway-nginx'
    static_configs:
      - targets: ['10.0.0.6:9101']


# Lintasarta
  - job_name: 'lintasarta'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.0.4:9100']

  - job_name: 'lintasarta-nginx'
    static_configs:
      - targets: ['10.0.0.4:9101']

# Soechi
  - job_name: 'soechi'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.0.3:9100']

  - job_name: 'soechi-nginx'
    static_configs:
      - targets: ['10.0.0.3:9101']



